### ISSUE TITLE
07.02.2022

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [gurbangurbanzade/Portfolio#1]
Salam, Qurban.🙂

- Yazdığınız kodları səliqəli yazmağa çalışın. Bunun üçün "Prettier - Code formatter" extensionundan istifadə edə bilərsiniz (Visual Studio Code editorundan istifadə edirsinizsə). Bu extension kodları avtomatik olaraq səliqəyə salır.  
- Commit mesajlarına xüsusi diqqət yetirin. Düzgün commit mesajı yazmaqla bağlı [**bu**](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali) məqalə faydalı ola bilər. 
- Qovluq və fayl strukturuna çox fikir verin. CSS fayllarını "css" adlı qovluğa əlavə etsəniz daha yaxşı olar. 

İndilik bu qədər. Uğurlar sizə!✌

**Comment by gurbangurbanzade** [comment]
Salam, Nəzrin. 😊
Feedback üçün təşəkkür edirəm.
Hörmətlə,
Qurban Qurbanzadə

7 fev 2022, B.E. 05:09 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:

**Comment by isbendiyarovanezrin** [comment]
Xoşdur.🤗
