### ISSUE TITLE
12.02.2022 | Tapşırıq 1

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [gurbangurbanzade/Portfolio#2]
Salam. 

- [ ] Tapşırıq yerinə yetirilməyib. 

@Gurban-Gurbanzade, tapşırığı tez bir zamanda yazmağa çalışın, yoxlayacam. :)

**Comment by gurbangurbanzade** [comment]
Düzgün repoya baxdığınızdan əmin olun.  :)

12 fev 2022, Ş. tarixində 06:28 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:
